### ISSUE TITLE
CW11 HD guide is showing WGN HD information.

### ISSUE THREAD

**Issue by cchalk** [littlestoneiptv/iptvsubs2pvriptvsimple3#1]
Hi,

Thanks for this add-on.
The CW11 HD guide is currently showing the programming for WGN channel.
Using prefer XMLTV in simple IPTV add-on shows the WGN logo for CW11 HD.

The current CW channel is CW23 Buffalo WNLO.

Thanks.

**Comment by cchalk** [comment]
Hi,

So line 56 in the WebGrab++.config.xml file has:

`<channel update="i" site="tvpassport.com" site_id="wgn-canada/4202" xmltv_id="ch85">WGN Canada</channel>`

If you change it:

`<channel update="i" site="zap2it.com" site_id="11714&amp;channel=11&amp;aid=zap2it" xmltv_id="ch85">CW11 HD</channel>`

Hopefully it should work now. :)

Thanks.

**Comment by littlestoneiptv** [comment]
Great. Will change it.
